throw new ${1:Exception}('${2}');
